#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 28 19:31:25 2017

@author: poojadonekal
"""
from instagram.client import InstagramAPI
import indicoio
import geocoder

access_token = "2008920528.bea2622.c43b3f70922f46a2b5b059e3dfd46550"
client_secret = "da9efc0b7b1848f5b592feca0d3f3fb5"
api = InstagramAPI(access_token=access_token, client_secret=client_secret)
recent_media, next_ = api.user_recent_media(user_id="2008920528", count=10)
photos=[]
captions=[]
latitude=[]
longitude=[]
tags=[]
for media in recent_media:
    captions.append(media.caption.text)
    photos.append('<img src="%s"/>' % media.images['standard_resolution'].url)
    tags.append(media.tags)
    if hasattr(media,'location'):
        latitude.append(media.location.point.latitude)
        longitude.append(media.location.point.longitude)

indicoio.config.api_key = '08bfe451983fff1dffdbac0a0e77d0a2'

happy=0
sad=0
for c in captions:
    if indicoio.sentiment(c)>0.5:
        happy=happy+1
    else:
        sad=sad+1
print "happy: " + str(happy)
print "sad:" +str(sad)                       
citiesvisited=[]                      
for l in range(len(latitude)): 
    g = geocoder.google([latitude[l],longitude[l]], method='reverse')
    print g.city
    citiesvisited.append(str(g.city))
print citiesvisited

